apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafbat-ui
spec:
  interval: 30m
  chart:
    spec:
      chart: kafka-ui
      sourceRef:
        kind: HelmRepository
        name: kafbat
        namespace: flux-system
  values:
    existingConfigMap: kafbat-ui-helm-values
